"use client";

import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { TextareaField, TextField } from "@/components/ui/Field";
import { PageHeader } from "@/components/ui/PageHeader";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { ApiError, apiFetch } from "@/lib/api/client";
import { uploadPrivateFile } from "@/lib/uploads/client";

type Uploaded = { id: string; name: string; mimeType: string; size: number };
export function TrialBalanceFlow() {
  const [file, setFile] = useState<File | null>(null); const [uploaded, setUploaded] = useState<Uploaded | null>(null); const [recipient, setRecipient] = useState(""); const [subject, setSubject] = useState("試算表送付のご連絡"); const [body, setBody] = useState("お世話になっております。\n試算表を添付いたします。ご確認をお願いいたします。"); const [stage, setStage] = useState("idle"); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false); const [status, setStatus] = useState<string | null>(null);
  function choose(selected: File | null) { setError(""); setUploaded(null); setStatus(null); if (!selected) { setFile(null); return; } if (!["text/csv", "application/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"].includes(selected.type)) { setError("CSV、XLS、XLSXを選択してください。"); return; } if (selected.size > 250 * 1024 * 1024) { setError("ファイルサイズは250MB以下にしてください。"); return; } setFile(selected); }
  async function upload() { if (!file) return; setStage("uploading"); setError(""); try { const response = await uploadPrivateFile(file, "trial_balance"); setUploaded(response.file); setStage("uploaded"); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "アップロードできませんでした"); setStage("idle"); } }
  async function send() { if (!uploaded) return; setStage("sending"); setError(""); try { const response = await apiFetch<{ email: { status: string }; auditSaved: boolean }>("/api/mail/send", { method: "POST", body: JSON.stringify({ recipient, subject, body, attachmentIds: [uploaded.id], idempotencyKey: crypto.randomUUID() }) }); setStatus(response.email.status); setConfirm(false); setStage("sent"); } catch (caught) { const apiError = caught instanceof ApiError ? caught : null; const payload = apiError?.payload as { auditSaved?: boolean; email?: { status?: string } } | undefined; setStatus(payload?.email?.status ?? "failed"); setError(`${apiError?.message ?? "送信できませんでした"}${payload?.auditSaved ? "。送信監査記録は保存されています。" : ""}`); setConfirm(false); setStage("failed"); } }
  return <div className="page"><PageHeader title="試算表送付" description="試算表を非公開で保存し、宛先と内容を確認して送信します。" />{error ? <div className="alert alert-danger" role="alert">{error}</div> : null}{status ? <div className={status === "sent" ? "alert alert-success" : "alert alert-danger"}><StatusBadge status={status} /> {status === "sent" ? "試算表を送信しました。" : "送信に失敗しました。"}</div> : null}<div className="upload-compose section"><section><h2 className="section-title">1. 試算表を登録</h2><label className="dropzone"><input type="file" accept=".csv,.xls,.xlsx" onChange={(event) => choose(event.target.files?.[0] ?? null)} /><span className="break-anywhere">{uploaded?.name ?? file?.name ?? "CSV、XLS、XLSXを選択"}</span><span className="muted">最大250MB · 非公開保存</span></label><div className="form-actions"><Button onClick={upload} busy={stage === "uploading"} disabled={!file || Boolean(uploaded)}>{uploaded ? "登録済み" : "試算表をアップロード"}</Button></div></section><section><h2 className="section-title">2. メールを作成</h2><div className="form-stack"><TextField label="宛先" type="email" requiredLabel value={recipient} onChange={(event) => setRecipient(event.target.value)} /><TextField label="件名" requiredLabel value={subject} maxLength={200} onChange={(event) => setSubject(event.target.value)} /><TextareaField label="本文" requiredLabel value={body} maxLength={20000} onChange={(event) => setBody(event.target.value)} /><div><span className="field-label">添付</span><p className="break-anywhere">{uploaded?.name ?? "試算表を先にアップロードしてください"}</p></div></div><div className="form-actions"><Button onClick={() => setConfirm(true)} disabled={!uploaded || !recipient || !subject || !body || stage === "sending"}>送信内容を確認</Button></div></section></div><ConfirmDialog open={confirm} onOpenChange={setConfirm} title="試算表を送信" description="次の内容で外部メールサービスから送信します。送信成否にかかわらず監査記録を保存します。" actions={<><Button variant="secondary" onClick={() => setConfirm(false)}>キャンセル</Button><Button busy={stage === "sending"} onClick={send}>試算表を送信</Button></>}><dl className="description-list"><dt>宛先</dt><dd>{recipient}</dd><dt>件名</dt><dd>{subject}</dd><dt>添付</dt><dd>{uploaded?.name}</dd></dl></ConfirmDialog></div>;
}
