"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { SelectField, TextField } from "@/components/ui/Field";
import { PageHeader } from "@/components/ui/PageHeader";
import { ErrorState, LoadingState } from "@/components/ui/State";
import { ApiError, apiFetch } from "@/lib/api/client";

type Choice = { id: string; name: string; loginId?: string }; type Membership = { userId: string; companyId: string; roleInCompany: string; user: Choice; company: Choice };
export function MembershipManager() {
  const [data, setData] = useState<{ memberships: Membership[]; users: Choice[]; companies: Choice[] } | null>(null); const [form, setForm] = useState({ userId: "", companyId: "", roleInCompany: "member" }); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [target, setTarget] = useState<Membership | null>(null);
  const load = useCallback(async () => { setError(""); try { setData(await apiFetch("/api/company_member")); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "読み込めませんでした"); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => data?.memberships.filter((item) => `${item.user.name} ${item.user.loginId} ${item.company.name}`.toLocaleLowerCase("ja").includes(query.toLocaleLowerCase("ja"))) ?? [], [data, query]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await apiFetch("/api/company_member", { method: "POST", body: JSON.stringify(form) }); setForm({ userId: "", companyId: "", roleInCompany: "member" }); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "所属を追加できませんでした"); } finally { setBusy(false); } }
  async function remove() { if (!target) return; setBusy(true); try { await apiFetch<void>("/api/company_member", { method: "DELETE", body: JSON.stringify({ userId: target.userId, companyId: target.companyId }) }); setTarget(null); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "所属を解除できませんでした"); setTarget(null); } finally { setBusy(false); } }
  return <div className="page"><PageHeader title="会社メンバー" description="利用者と会社の所属を管理します。" />{error && data ? <div className="alert alert-danger" role="alert">{error}</div> : null}{!data ? error ? <ErrorState message={error} onRetry={load} /> : <LoadingState /> : <><form className="form-section" onSubmit={create}><h2>所属を追加</h2><div className="form-grid"><SelectField label="利用者" requiredLabel value={form.userId} onChange={(event) => setForm({ ...form, userId: event.target.value })}><option value="">選択してください</option>{data.users.map((user) => <option value={user.id} key={user.id}>{user.name}（{user.loginId}）</option>)}</SelectField><SelectField label="会社" requiredLabel value={form.companyId} onChange={(event) => setForm({ ...form, companyId: event.target.value })}><option value="">選択してください</option>{data.companies.map((company) => <option value={company.id} key={company.id}>{company.name}</option>)}</SelectField><SelectField label="会社内権限" value={form.roleInCompany} onChange={(event) => setForm({ ...form, roleInCompany: event.target.value })}><option value="member">メンバー</option><option value="accountant">会計担当</option><option value="admin">会社管理者</option><option value="owner">オーナー</option></SelectField></div><p className="muted">会社管理者は会社設定を編集できます。オーナーの編集権限は現行ポリシーでは付与されません。</p><div className="form-actions"><Button type="submit" busy={busy} disabled={!form.userId || !form.companyId}>所属を追加</Button></div></form><section className="section"><div className="toolbar"><TextField label="検索" className="search-field" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="利用者または会社" /></div><div style={{ overflowX: "auto" }}><table className="admin-table"><thead><tr><th>利用者</th><th>会社</th><th>会社内権限</th><th>操作</th></tr></thead><tbody>{filtered.map((item) => <tr key={`${item.userId}:${item.companyId}`}><td>{item.user.name}<div className="row-meta">{item.user.loginId}</div></td><td>{item.company.name}</td><td>{item.roleInCompany}</td><td><Button variant="ghost" onClick={() => setTarget(item)}>解除</Button></td></tr>)}</tbody></table></div></section></>}<ConfirmDialog open={Boolean(target)} onOpenChange={(open) => { if (!open) setTarget(null); }} title="会社所属を解除" description={`${target?.user.name ?? "選択した利用者"}の${target?.company.name ?? "会社"}への所属を解除します。最後の会社管理者や自分自身の所属は解除できません。`} actions={<><Button variant="secondary" onClick={() => setTarget(null)}>キャンセル</Button><Button variant="danger" busy={busy} onClick={remove}>所属を解除</Button></>} /></div>;
}
