"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/Button";
import { SelectField, TextField } from "@/components/ui/Field";
import { PageHeader } from "@/components/ui/PageHeader";
import { ErrorState, LoadingState, NeedsCompanyState } from "@/components/ui/State";
import { ApiError, apiFetch } from "@/lib/api/client";
import { fiscalYearInTokyo, todayInTokyo } from "@/lib/date/business-date";

type Item = { id: string; name: string }; type Check = { id: string; itemId: string; fiscalYear: number; month: number; checked: boolean }; type Data = { fiscalYear: number; items: Item[]; checks: Check[] };
const months = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3];

export function AccountingChecklist() {
  const [year, setYear] = useState(() => fiscalYearInTokyo()); const [mobileMonth, setMobileMonth] = useState(() => Number(todayInTokyo().slice(5, 7))); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [needsCompany, setNeedsCompany] = useState(false); const saving = useRef(new Set<string>()); const [newName, setNewName] = useState(""); const [adding, setAdding] = useState(false);
  const load = useCallback(async () => { setError(""); setNeedsCompany(false); setData(null); try { setData(await apiFetch<Data>(`/api/accounting-checklist?fiscalYear=${year}`)); } catch (caught) { if (caught instanceof ApiError && caught.status === 404) setNeedsCompany(true); else setError(caught instanceof ApiError ? caught.message : "読み込めませんでした"); } }, [year]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const checked = useMemo(() => new Set(data?.checks.filter((check) => check.checked).map((check) => `${check.itemId}:${check.month}`)), [data]);
  async function toggle(item: Item, month: number) { if (!data) return; const key = `${item.id}:${month}`; if (saving.current.has(key)) return; saving.current.add(key); const next = !checked.has(key); const previousCheck = data.checks.find((check) => check.itemId === item.id && check.month === month); setData({ ...data, checks: [...data.checks.filter((check) => !(check.itemId === item.id && check.month === month)), { id: key, itemId: item.id, fiscalYear: year, month, checked: next }] }); try { await apiFetch("/api/accounting-checklist/checks", { method: "PATCH", body: JSON.stringify({ itemId: item.id, fiscalYear: year, month, checked: next }) }); } catch (caught) { setData((current) => current ? { ...current, checks: [...current.checks.filter((check) => !(check.itemId === item.id && check.month === month)), ...(previousCheck ? [previousCheck] : [])] } : current); setError(caught instanceof ApiError ? caught.message : "チェックを保存できませんでした"); } finally { saving.current.delete(key); } }
  async function add(event: React.FormEvent) { event.preventDefault(); if (!newName) return; setAdding(true); setError(""); try { await apiFetch("/api/accounting-checklist/items", { method: "POST", body: JSON.stringify({ name: newName }) }); setNewName(""); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "項目を追加できませんでした"); } finally { setAdding(false); } }
  if (needsCompany) return <div className="page"><PageHeader title="会計資料チェック" /><NeedsCompanyState /></div>;
  if (error && !data) return <div className="page"><PageHeader title="会計資料チェック" /><ErrorState message={error} onRetry={load} /></div>;
  return <div className="page"><PageHeader title="会計資料チェック" description="4月から翌3月までの資料受領状況を管理します。" /><div className="toolbar"><SelectField label="年度" value={year} onChange={(event) => setYear(Number(event.target.value))}>{Array.from({ length: 101 }, (_, index) => 2100 - index).map((value) => <option value={value} key={value}>{value}年度</option>)}</SelectField><form onSubmit={add} className="toolbar" style={{ marginBottom: 0, flex: 1 }}><TextField label="項目を追加" className="search-field" value={newName} maxLength={100} onChange={(event) => setNewName(event.target.value)} placeholder="資料名" /><Button type="submit" busy={adding} disabled={!newName}>項目を追加</Button></form></div>{error ? <div className="alert alert-danger" role="alert">{error}<button className="button button-ghost" onClick={load}>再試行</button></div> : null}{!data ? <LoadingState /> : <><div className="desktop-checklist checklist-wrap"><table className="checklist"><caption>{year}年度 会計資料チェック</caption><thead><tr><th scope="col">資料</th>{months.map((month) => <th scope="col" key={month}>{month}月</th>)}</tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><th scope="row">{item.name}</th>{months.map((month) => { const key = `${item.id}:${month}`; return <td key={month}><input className="check-toggle" type="checkbox" aria-label={`${item.name} ${month}月`} checked={checked.has(key)} onChange={() => toggle(item, month)} /></td>; })}</tr>)}</tbody></table></div><div className="mobile-checklist"><SelectField label="表示する月" value={mobileMonth} onChange={(event) => setMobileMonth(Number(event.target.value))}>{months.map((month) => <option value={month} key={month}>{month}月</option>)}</SelectField>{data.items.map((item) => { const key = `${item.id}:${mobileMonth}`; return <label className="mobile-check-row" key={item.id}><span>{item.name}</span><span><input className="check-toggle" type="checkbox" aria-label={`${item.name} ${mobileMonth}月`} checked={checked.has(key)} onChange={() => toggle(item, mobileMonth)} /></span></label>; })}</div></>}</div>;
}
