"use client";

import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { PageHeader } from "@/components/ui/PageHeader";
import { ApiError, apiFetch } from "@/lib/api/client";
import { uploadPrivateFile } from "@/lib/uploads/client";

type Rating = { score: number; grade: string; aiComment: string; highlights: string[]; aiSource: string; scoreVersion: string; promptVersion: string };
const allowed = ["application/pdf", "text/csv", "application/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"];

export function RatingFlow() {
  const [file, setFile] = useState<File | null>(null); const [stage, setStage] = useState("idle"); const [error, setError] = useState(""); const [result, setResult] = useState<Rating | null>(null); const [cached, setCached] = useState(false);
  function choose(selected: File | null) { setError(""); setResult(null); if (!selected) { setFile(null); return; } if (!allowed.includes(selected.type)) { setError("PDF、CSV、XLS、XLSXを選択してください。"); return; } if (selected.size > 250 * 1024 * 1024) { setError("ファイルサイズは250MB以下にしてください。"); return; } setFile(selected); }
  async function run() { if (!file) return; setError(""); setStage(file.size <= 20 * 1024 * 1024 ? "ファイルを検証中" : "アップロード準備中"); try { const upload = await uploadPrivateFile(file, "rating"); setStage("簡易評価を作成中"); const response = await apiFetch<{ rating: Rating; cached: boolean }>("/api/rating/finalize", { method: "POST", body: JSON.stringify({ fileId: upload.file.id }) }); setResult(response.rating); setCached(response.cached); setStage("done"); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "評価を完了できませんでした"); setStage("error"); } }
  return <div className="page"><PageHeader title="財務格付け" description="書類のメタ情報を基にした簡易評価を確認します。" /><div className="alert"><p><strong>AIによる簡易助言</strong></p><p>この結果は、ファイル名・形式・サイズ等の限定的な情報を基にした簡易評価です。提出書類の内容を全文解析した財務判断ではありません。</p></div><section className="section"><h2 className="section-title">書類を選択</h2><label className="dropzone"><input type="file" accept=".pdf,.csv,.xls,.xlsx" onChange={(event) => choose(event.target.files?.[0] ?? null)} /><span>{file ? file.name : "PDF、CSV、XLS、XLSX（最大250MB）"}</span>{file ? <span className="muted tabular">{Math.ceil(file.size / 1024).toLocaleString("ja-JP")} KB · 非公開で保存</span> : null}</label>{error ? <div className="alert alert-danger" role="alert" style={{ marginTop: 12 }}>{error}</div> : null}<div className="form-actions"><Button busy={stage !== "idle" && stage !== "done" && stage !== "error"} disabled={!file} onClick={run}>評価を実行</Button></div>{stage !== "idle" && stage !== "done" && stage !== "error" ? <p aria-live="polite" className="muted">{stage}</p> : null}</section>{result ? <section className="section" aria-labelledby="rating-result"><h2 className="section-title" id="rating-result">評価結果 {cached ? <span className="status-badge">保存済み結果</span> : null}</h2><div className="metric-row"><div className="metric"><span className="muted">簡易スコア</span><strong>{result.score}<small>/100</small></strong></div><div className="metric"><span className="muted">グレード</span><strong>{result.grade}</strong></div></div><h3 className="section-title" style={{ marginTop: 20 }}>{result.aiSource === "gemini" ? "AIコメント" : "一般的な改善例"}</h3><p>{result.aiComment}</p><ul>{result.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul><details><summary>算定方法</summary><p className="muted">ファイル名、MIME形式、サイズから算定しています。書類本文は解析していません。スコア版: {result.scoreVersion}</p></details></section> : null}</div>;
}
