param(
  [string]$From = ".env.local",
  [string]$To   = ".env"
)
$ErrorActionPreference = "Stop"
if (!(Test-Path $From)) { throw "From not found: $From" }

$need = @("DATABASE_URL","DIRECT_URL")
$lines = Get-Content $From

$out = @(
  "# Autogenerated for Prisma CLI. DO NOT COMMIT.",
  "# Source: $From"
)

foreach ($k in $need) {
  $line = $lines | Where-Object { $_ -match ("^" + [regex]::Escape($k) + "=") } | Select-Object -First 1
  if (-not $line) { throw "Missing key in ${From}: $k" }
  $out += $line
}

$out | Set-Content -Encoding UTF8 $To
Write-Host "[OK] Wrote $To (values not printed)."
